# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a36ed76aa5eb24416179106a4ce82700d4c8da41e1fc98c1fd1572d74fae7a354bd3f8732914fc3b980317dde7dd0f0b8d0c1683c0b228358a162c49d7a1d30

test:
  secret_key_base: c4095ee043dd5c12d94c9dd02cbb944f5682d2a019cd163f7b1feeb1ddfd1a4a0cdd41f858ec86c775e8aa0f84f563e3acf1586962dd7446bdb8834f446e51db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
